# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lhx < Formula
  desc "Expose localhost to the internet instantly"
  homepage "https://localhoxt.com"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/OmerAhmedQuadri/localhoxt.com/releases/download/v0.1.0/lhx_0.1.0_darwin_amd64.tar.gz"
      sha256 "db73896ba0f33c2a96081b3ee33c191389caf9ecb007711b93d22a9e458a1626"

      define_method(:install) do
        bin.install "lhx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/OmerAhmedQuadri/localhoxt.com/releases/download/v0.1.0/lhx_0.1.0_darwin_arm64.tar.gz"
      sha256 "35626830065ca3448b455f05c1e6ab2181c0bff0a8c967c26920fee9ff44ff2f"

      define_method(:install) do
        bin.install "lhx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/OmerAhmedQuadri/localhoxt.com/releases/download/v0.1.0/lhx_0.1.0_linux_amd64.tar.gz"
      sha256 "cb717af611e51f51987b39e9a848c78d939734af523101bfeecdeaefb1209f7e"
      define_method(:install) do
        bin.install "lhx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/OmerAhmedQuadri/localhoxt.com/releases/download/v0.1.0/lhx_0.1.0_linux_arm64.tar.gz"
      sha256 "986c2593a49e4c08ee1e0a904b0bf4c758ed2611b1938d1f3d9c88b1eb93c193"
      define_method(:install) do
        bin.install "lhx"
      end
    end
  end

  test do
    system "#{bin}/lhx", "version"
  end
end
