# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lhx < Formula
  desc "Expose localhost to the internet instantly"
  homepage "https://localhoxt.com"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/OmerAhmedQuadri/localhoxt.com/releases/download/v0.1.0/lhx_0.1.0_darwin_amd64.tar.gz"
      sha256 "710aea24f4f5c5a0f45eed1c5a703a9a50a1e0dbbcca0dd72dbf56f02e411631"

      define_method(:install) do
        bin.install "lhx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/OmerAhmedQuadri/localhoxt.com/releases/download/v0.1.0/lhx_0.1.0_darwin_arm64.tar.gz"
      sha256 "546405dd118db64e87ed917e63653eb18f62b8619706dc3e4b2c16eca1afa4a9"

      define_method(:install) do
        bin.install "lhx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/OmerAhmedQuadri/localhoxt.com/releases/download/v0.1.0/lhx_0.1.0_linux_amd64.tar.gz"
      sha256 "de495d0ed1e43d16570307ae3fa87c79937d44d2931751526d498d6f2ec54960"
      define_method(:install) do
        bin.install "lhx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/OmerAhmedQuadri/localhoxt.com/releases/download/v0.1.0/lhx_0.1.0_linux_arm64.tar.gz"
      sha256 "05c2d00ce61a1104b65b19c59a13b462f549634667adc7355fcc655af35ce5b3"
      define_method(:install) do
        bin.install "lhx"
      end
    end
  end

  test do
    system "#{bin}/lhx", "version"
  end
end
