# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lhx < Formula
  desc "Expose localhost to the internet instantly"
  homepage "https://localhoxt.com"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/OmerAhmedQuadri/localhoxt.com/releases/download/v0.1.0/lhx_0.1.0_darwin_amd64.tar.gz"
      sha256 "d1aca651e26ab990dcfb2c2fd04a0438917ff29ca5dfa554c96f22be64a5301e"

      define_method(:install) do
        bin.install "lhx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/OmerAhmedQuadri/localhoxt.com/releases/download/v0.1.0/lhx_0.1.0_darwin_arm64.tar.gz"
      sha256 "f9ef3f62196a1146d2c6529dfa5b657eb8329b9984b38a2c924716f2034c6be8"

      define_method(:install) do
        bin.install "lhx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/OmerAhmedQuadri/localhoxt.com/releases/download/v0.1.0/lhx_0.1.0_linux_amd64.tar.gz"
      sha256 "273673ff1c8d959b829ecb09b5c5e6ba75c09a478a32da808a132a88c058aa3c"
      define_method(:install) do
        bin.install "lhx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/OmerAhmedQuadri/localhoxt.com/releases/download/v0.1.0/lhx_0.1.0_linux_arm64.tar.gz"
      sha256 "df4effac84d195b7ec812d8772888ca4596c0dfa5cf6b0d0d6512bcb33bacaf7"
      define_method(:install) do
        bin.install "lhx"
      end
    end
  end

  test do
    system "#{bin}/lhx", "version"
  end
end
